default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  user: postgres
  password: p@ssw0rd

development:
  <<: *default
  database: postgres96tz_development

test: &test
  <<: *default
  database: postgres96tz_test
